### ISSUE TITLE
LIGMA

### ISSUE THREAD

**Issue by MisterSheeple** [Omniarchive/Website#7]
Now that I have your attention, I'd like to propose that we remove RetroWrapper from the FAQ, as it's now been inactive for a year.

**Comment by NeRdTheNed** [comment]
I've just released [a new update](https://github.com/NeRdTheNed/RetroWrapper/releases/)!

**Comment by MisterSheeple** [comment]
Closing this because our website is no longer open source and the repo is no longer being updated.
